[workspace]

[package]
name = "ac-library-rs"
version = "0.1.0"
authors = ["rust-lang-ja Developers"]
edition = "2018"
description = "A Rust port of AtCoder Library (ACL)."
license = "CC0-1.0"
repository = "https://github.com/rust-lang-ja/ac-library-rs"
keywords = ["competitive"]
categories = ["algorithms", "data-structures"]
publish = false

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "./katex-header.html"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
__acl_convolution = { package = "acl_convolution", version = "0.1.0", path = "./acl_convolution" }
__acl_dsu         = { package = "acl_dsu"        , version = "0.1.0", path = "./acl_dsu"         }
__acl_fenwicktree = { package = "acl_fenwicktree", version = "0.1.0", path = "./acl_fenwicktree" }
__acl_lazysegtree = { package = "acl_lazysegtree", version = "0.1.0", path = "./acl_lazysegtree" }
__acl_math        = { package = "acl_math"       , version = "0.1.0", path = "./acl_math"        }
__acl_maxflow     = { package = "acl_maxflow"    , version = "0.1.0", path = "./acl_maxflow"     }
__acl_mincostflow = { package = "acl_mincostflow", version = "0.1.0", path = "./acl_mincostflow" }
__acl_modint      = { package = "acl_modint"     , version = "0.1.0", path = "./acl_modint"      }
__acl_scc         = { package = "acl_scc"        , version = "0.1.0", path = "./acl_scc"         }
__acl_segtree     = { package = "acl_segtree"    , version = "0.1.0", path = "./acl_segtree"     }
__acl_string      = { package = "acl_string"     , version = "0.1.0", path = "./acl_string"      }
__acl_twosat      = { package = "acl_twosat"     , version = "0.1.0", path = "./acl_twosat"      }
