[package]
name = "ac-library-rs"
version = "0.1.0"
authors = ["rust-lang-ja Developers"]
edition = "2018"
description = "A Rust port of AtCoder Library (ACL)."
license = "CC0-1.0"
repository = "https://github.com/rust-lang-ja/ac-library-rs"
keywords = ["competitive"]
categories = ["algorithms", "data-structures"]
publish = false

[[example]]
name = "practice2_d_maxflow"
path = "examples/practice2_d_maxflow.rs"
required-features = ["maxflow"]

[[example]]
name = "practice2_j_segment_tree"
path = "examples/practice2_j_segment_tree.rs"
required-features = ["segtree"]

[[example]]
name = "practice2_k_range_affine_range_sum"
path = "examples/practice2_k_range_affine_range_sum.rs"
required-features = ["lazysegtree", "modint"]

[[example]]
name = "practice2_l_lazy_segment_tree"
path = "examples/practice2_l_lazy_segment_tree.rs"
required-features = ["lazysegtree"]

[features]
default = ["convolution", "dsu", "fenwicktree", "lazysegtree", "math", "maxflow", "mincostflow", "modint", "scc", "segtree", "string", "twosat"]
convolution = ["modint"]
dsu = []
fenwicktree = []
lazysegtree = ["segtree"]
math = []
maxflow = []
mincostflow = []
modint = []
scc = []
segtree = []
string = []
twosat = []

[dependencies]

[dev-dependencies]
proconio = "=0.3.6"
rand = "0.7.3"
